# Lorem Ipsum

name: ipsum
parent: default

matches:
  # Sentence
  - trigger: "Lorem S"
    replace: "Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua."

  - trigger: "Lorem 1S"
    replace: "{{output}}"
    vars:
      - name: output
        type: random
        params:
          choices:
            - "Curabitur blandit tempus ardua ridiculus sed magna."
            - "Inmensae subtilitatis, obscuris et malesuada fames."
            - "Paullum deliquit, ponderibus modulisque suis ratio utitur."
            - "Pellentesque habitant morbi tristique senectus et netus."
            - "A communi observantia non est recedendum."
            - "Unam incolunt Belgae, aliam Aquitani, tertiam."
            - "Magna pars studiorum, prodita quaerimus."
            - "Gallia est omnis divisa in partes tres, quarum."
            - "Phasellus laoreet lorem vel dolor tempus vehicula."
            - "Cras mattis iudicium purus sit amet fermentum."
            - "Nec dubitamus multa iter quae et nos invenerat."
            - "Quo usque tandem abutere, Catilina, patientia nostra?"
            - "Curabitur est gravida et libero vitae dictum."
            - "Quisque ut dolor gravida, placerat libero vel, euismod."
            - "Ullamco laboris nisi ut aliquid ex ea commodi consequat."

  # Multiples sentences
  - trigger: "Lorem 2S"
    replace: "{{one}} {{two}}"
    vars:
      - name: one
        type: match
        params:
          trigger: "Lorem S"
      - name: two
        type: match
        params:
          trigger: "Lorem 1S"
  - trigger: "Lorem 3S"
    replace: "{{two}} {{three}}"
    vars:
      - name: two
        type: match
        params:
          trigger: "Lorem 2S"
      - name: three
        type: match
        params:
          trigger: "Lorem 1S"
  - trigger: "Lorem 4S"
    replace: "{{three}} {{four}}"
    vars:
      - name: three
        type: match
        params:
          trigger: "Lorem 2S"
      - name: four
        type: match
        params:
          trigger: "Lorem 2S"
  - trigger: "Lorem 5S"
    replace: "{{four}} {{five}}"
    vars:
      - name: four
        type: match
        params:
          trigger: "Lorem 3S"
      - name: five
        type: match
        params:
          trigger: "Lorem 2S"

  # Paragraph
  - trigger: "Lorem P"
    replace: "Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Donec sed odio operae, eu vulputate felis rhoncus. Salutantibus vitae elit libero, a pharetra augue. Nihil hic munitissimus habendi senatus locus, nihil horum? A communi observantia non est recedendum."

  - trigger: "Lorem 1P"
    replace: "{{output}}"
    vars:
      - name: output
        type: random
        params:
          choices:
            - "Curabitur blandit tempus ardua ridiculus sed magna. Sed haec quis possit intrepidus aestimare tellus. Quisque ut dolor gravida, placerat libero vel, euismod. Plura mihi bona sunt, inclinet, amari petere vellent."
            - "Fictum, deserunt mollit anim laborum astutumque! Quisque placerat facilisis egestas cillum dolore. Nec dubitamus multa iter quae et nos invenerat. Contra legem facit qui id facit quod lex prohibet. Quam diu etiam furor iste tuus nos eludet?"
            - "Plura mihi bona sunt, inclinet, amari petere vellent. Ab illo tempore, ab est sed immemorabili. Ullamco laboris nisi ut aliquid ex ea commodi consequat. Quae vero auctorem tractata ab fiducia dicuntur. At nos hinc posthac, sitientis piros Afros."
            - "Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Me non paenitet nullum festiviorem excogitasse ad hoc. Ambitioni dedisse scripsisse iudicaretur. Unam incolunt Belgae, aliam Aquitani, tertiam. Morbi fringilla convallis sapien, id pulvinar odio volutpat. A communi observantia non est recedendum."
            - "Quisque ut dolor gravida, placerat libero vel, euismod. Ambitioni dedisse scripsisse iudicaretur. Donec sed odio operae, eu vulputate felis rhoncus. Nihilne te nocturnum praesidium Palati, nihil urbis vigiliae."
            - "Fabio vel iudice vincam, sunt in culpa qui officia. Inmensae subtilitatis, obscuris et malesuada fames. Ambitioni dedisse scripsisse iudicaretur. Nec dubitamus multa iter quae et nos invenerat. Petierunt uti sibi concilium totius Galliae in diem certam indicere."
            - "A communi observantia non est recedendum. Vivamus sagittis lacus vel augue laoreet rutrum faucibus. Nihilne te nocturnum praesidium Palati, nihil urbis vigiliae."
            - "Non equidem invideo, miror magis posuere velit aliquet. Quisque placerat facilisis egestas cillum dolore. Curabitur blandit tempus ardua ridiculus sed magna. Contra legem facit qui id facit quod lex prohibet. Petierunt uti sibi concilium totius Galliae in diem certam indicere."
            - "Ab illo tempore, ab est sed immemorabili. Cum sociis natoque penatibus et magnis dis parturient. Quam diu etiam furor iste tuus nos eludet? Ut enim ad minim veniam, quis nostrud exercitation."
            - "Nihilne te nocturnum praesidium Palati, nihil urbis vigiliae. Salutantibus vitae elit libero, a pharetra augue. Quam diu etiam furor iste tuus nos eludet? Fabio vel iudice vincam, sunt in culpa qui officia. Quam temere in vitiis, legem sancimus haerentia. Quisque ut dolor gravida, placerat libero vel, euismod."
            - "Morbi fringilla convallis sapien, id pulvinar odio volutpat. Hi omnes lingua, institutis, legibus inter se differunt. Non equidem invideo, miror magis posuere velit aliquet. Quid securi etiam tamquam eu fugiat nulla pariatur. Inmensae subtilitatis, obscuris et malesuada fames. Fictum, deserunt mollit anim laborum astutumque!"
            - "Cum sociis natoque penatibus et magnis dis parturient. Curabitur blandit tempus ardua ridiculus sed magna. Salutantibus vitae elit libero, a pharetra augue."
            - "Petierunt uti sibi concilium totius Galliae in diem certam indicere. Morbi fringilla convallis sapien, id pulvinar odio volutpat. A communi observantia non est recedendum."
            - "Phasellus laoreet lorem vel dolor tempus vehicula. Idque Caesaris facere voluntate liceret: sese habere. Ab illo tempore, ab est sed immemorabili. Mercedem aut nummos unde unde extricat, amaras. Praeterea iter est quasdam res quas ex communi."

  # Multiples paragraphs
  - trigger: "Lorem 2P"
    replace: "{{one}}\n{{two}}"
    vars:
      - name: one
        type: match
        params:
          trigger: "Lorem P"
      - name: two
        type: match
        params:
          trigger: "Lorem 1P"
  - trigger: "Lorem 3P"
    replace: "{{two}}\n{{three}}"
    vars:
      - name: two
        type: match
        params:
          trigger: "Lorem 2P"
      - name: three
        type: match
        params:
          trigger: "Lorem 1P"
  - trigger: "Lorem 4P"
    replace: "{{three}}\n{{four}}"
    vars:
      - name: three
        type: match
        params:
          trigger: "Lorem 2P"
      - name: four
        type: match
        params:
          trigger: "Lorem 2P"
  - trigger: "Lorem 5P"
    replace: "{{four}}\n{{five}}"
    vars:
      - name: four
        type: match
        params:
          trigger: "Lorem 3P"
      - name: five
        type: match
        params:
          trigger: "Lorem 2P"


  # HTML Lists
  - trigger: "Lorem li"
    replace: "<li>Lorem ipsum</li>"

  - trigger: "Lorem 1li"
    replace: "{{output}}"
    vars:
      - name: output
        type: random
        params:
          choices:
            - "<li>Curabitur blandit</li>"
            - "<li>Inmensae subtilitatis</li>"
            - "<li>Paullum deliquit</li>"
            - "<li>Pellentesque habitant</li>"
            - "<li>A communi</li>"
            - "<li>Unam incolunt</li>"
            - "<li>Magna pars</li>"
            - "<li>Gallia est</li>"
            - "<li>Phasellus laoreet</li>"
            - "<li>Cras mattis</li>"
            - "<li>Nec dubitamus</li>"
            - "<li>Quo usque</li>"
            - "<li>Curabitur est</li>"
            - "<li>Quisque ut</li>"
            - "<li>Ullamco laboris</li>"

  - trigger: "Lorem 2li"
    replace: "{{one}}\n{{two}}"
    vars:
      - name: one
        type: match
        params:
          trigger: "Lorem li"
      - name: two
        type: match
        params:
          trigger: "Lorem 1li"
  - trigger: "Lorem 3li"
    replace: "{{two}}\n{{three}}"
    vars:
      - name: two
        type: match
        params:
          trigger: "Lorem 2li"
      - name: three
        type: match
        params:
          trigger: "Lorem 1li"
  - trigger: "Lorem 4li"
    replace: "{{three}}\n{{four}}"
    vars:
      - name: three
        type: match
        params:
          trigger: "Lorem 2li"
      - name: four
        type: match
        params:
          trigger: "Lorem 2li"
  - trigger: "Lorem 5li"
    replace: "{{four}}\n{{five}}"
    vars:
      - name: four
        type: match
        params:
          trigger: "Lorem 3li"
      - name: five
        type: match
        params:
          trigger: "Lorem 2li"

  # HTML UL
  - trigger: "Lorem ul"
    replace: "<ul>\n{{one}}\n{{two}}\n{{three}}\n{{four}}\n{{five}}\n</ul>"
    vars:
      - name: one
        type: match
        params:
          trigger: "Lorem 1li"
      - name: two
        type: match
        params:
          trigger: "Lorem 1li"
      - name: three
        type: match
        params:
          trigger: "Lorem 1li"
      - name: four
        type: match
        params:
          trigger: "Lorem 1li"
      - name: five
        type: match
        params:
          trigger: "Lorem 1li"

  # HTML OL
  - trigger: "Lorem ol"
    replace: "<ol>\n{{one}}\n{{two}}\n{{three}}\n{{four}}\n{{five}}\n</ol>"
    vars:
      - name: one
        type: match
        params:
          trigger: "Lorem 1li"
      - name: two
        type: match
        params:
          trigger: "Lorem 1li"
      - name: three
        type: match
        params:
          trigger: "Lorem 1li"
      - name: four
        type: match
        params:
          trigger: "Lorem 1li"
      - name: five
        type: match
        params:
          trigger: "Lorem 1li"
